const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 144. Large media and entertainment companies undergoing digital transformation face a data fragmentation bottleneck where dozens of disconnected applications, hundreds of downstream tool integrations, and siloed customer data prevent personalization at scale — and without a centralized customer data platform, engineering teams spend more time maintaining data pipelines than building user experiences
- **Category:** Integration
- **Friction:** Large media and entertainment companies undergoing digital transformation face a data fragmentation bottleneck where dozens of disconnected applications, hundreds of downstream tool integrations, and siloed customer data prevent personalization at scale. 'Each of FOX's digital brands had 40+ applications that were integrated to 30+ downstream tools, resulting in nearly 1,200 integrations the engineering team had to build and maintain. In order to make customer data useful, engineering teams had to spend enormous amounts of time cleaning and standardizing data and connecting tools.' Without a unified customer data platform, engineering capacity is consumed by pipeline maintenance instead of product innovation, and personalization ambitions remain aspirational.
- **Source:** https://customers.twilio.com/en-us/fox
- **Severity:** High. Named exec: Daryl Bowden (Executive Vice President of Technology, FOX Corporation). Quantified: 75% reduction in customer data QA labor; >$1.2M in value of time saved annually; $622K/year in manual QA effort cost reduction; $500K/year in avoided wasted downstream data user productivity; 376% more visitors to FOX Sports 'For You'; 31% increase in stories consumed; 347% lift in clicks/visits to recommended content on FOX Nation. Quote: 'When you use any of our apps, you should be greeted like an old friend. When we deliver an ad to you, it should be relevant. When we suggest content to you, it should be in line with your tastes. This is all thanks to Twilio Segment.'

### 145. Consumer brands with expanding digital footprints face a customer acquisition bottleneck where siloed data prevents personalization, generic messaging drives low ROAS, and without a unified customer data platform, marketing teams cannot build hyper-targeted audiences — creating a cycle where ad spend is wasted on broad audiences that convert poorly
- **Category:** Integration
- **Friction:** Consumer brands with expanding digital footprints face a customer acquisition bottleneck where siloed data prevents personalization, generic messaging drives low ROAS. 'Data silos prevented collaboration around the customer experience, and the marketing team was unable to personalize campaigns based on consumer behavior. This led to low return on ad spend (ROAS) due to generic / poorly targeted messaging.' Without a customer data platform that unifies touchpoints and enables precise audience segmentation, brands are forced to spend on broad targeting that wastes budget on low-intent customers rather than high-value segments.
- **Source:** https://customers.twilio.com/en-us/dominos
- **Severity:** High. Quantified: 65% decrease in customer acquisition cost (CPA); 700% increase in ROAS on Google campaigns; 23% incremental increase in Facebook conversions for customer acquisition; 16% incremental increase in Facebook conversions for customer retention. Context: Domino's Mexico serves 550,000+ families per week across 718 stores, with digital channels representing more than half of all global retail sales.
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 144 and 145 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Integration","Specific_Friction":"Large media and entertainment companies undergoing digital transformation face a data fragmentation bottleneck where dozens of disconnected applications, hundreds of downstream tool integrations, and siloed customer data prevent personalization at scale. 'Each of FOX's digital brands had 40+ applications that were integrated to 30+ downstream tools, resulting in nearly 1,200 integrations the engineering team had to build and maintain. In order to make customer data useful, engineering teams had to spend enormous amounts of time cleaning and standardizing data and connecting tools.' Without a unified customer data platform, engineering capacity is consumed by pipeline maintenance instead of product innovation.","Source_URL":"https://customers.twilio.com/en-us/fox","Severity_Impact":"High. Named exec: Daryl Bowden (EVP Technology, FOX Corporation). Quantified: 75% reduction in customer data QA labor; >$1.2M in value of time saved annually; $622K/year in manual QA cost reduction; $500K/year avoided productivity waste; 376% more visitors to FOX Sports 'For You'; 31% increase in stories consumed."}
{"Pain_Point_Category":"Integration","Specific_Friction":"Consumer brands with expanding digital footprints face a customer acquisition bottleneck where siloed data prevents personalization, generic messaging drives low ROAS. 'Data silos prevented collaboration around the customer experience, and the marketing team was unable to personalize campaigns based on consumer behavior. This led to low return on ad spend (ROAS) due to generic / poorly targeted messaging.' Without a customer data platform that unifies touchpoints and enables precise audience segmentation, brands waste ad spend on broad audiences that convert poorly.","Source_URL":"https://customers.twilio.com/en-us/dominos","Severity_Impact":"High. Quantified: 65% decrease in customer acquisition cost (CPA); 700% increase in ROAS on Google; 23% incremental increase in Facebook conversions for acquisition; 16% for retention. Context: Domino's Mexico serves 550,000+ families/week across 718 stores."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 144 and 145 to jsonl');