const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 140. Enterprise companies managing multiple compliance frameworks and large vendor portfolios face a GRC operational ceiling where manual evidence collection, fragmented controls, and disconnected systems create an unsustainable burden on trust and security teams — and without a unified, AI-powered platform, the choice is between compliance bottlenecks or expensive headcount
- **Category:** Security
- **Friction:** Enterprise companies managing multiple compliance frameworks and large vendor portfolios face a GRC operational ceiling where manual evidence collection, fragmented controls, and disconnected systems create an unsustainable burden. 'Samsara's GRC team was responsible for maintaining compliance across 10 frameworks, managing a portfolio of more than 600 vendors, and supporting security reviews at every stage of the sales cycle. With 820+ controls across frameworks and ~130 vendor reviews per month, the team was nearing an operational ceiling.' Without a unified platform, trust teams spend hours manually stitching together audit evidence, drowning in disconnected workflows while security reviews bottleneck revenue-critical sales cycles.
- **Source:** https://www.vanta.com/customers/samsara
- **Severity:** High. Named exec: Nick Hardy (Senior Director of Security, GRC, and Program Management, Samsara). Quantified: 820 controls consolidated to 260 (68% reduction); 1,200 evidence items mapped across 10 frameworks; SME interview time reduced from 70 to 40 hours per audit cycle (43% reduction); up to 50% faster vendor reviews; $150M+ in influenced revenue; $300K+ ROI in year one; ~130 vendor reviews per month managed at scale. Quote: 'Vanta is very clearly building an Agentic platform that allows us to automate a variety of different GRC functions.'

### 141. Large enterprises with extensive customer bases face a trust operations bottleneck where manual security questionnaire responses and document distribution create a sales cycle drag that scales poorly — and without a self-service Trust Center, trust teams become the rate-limiting factor in every deal
- **Category:** Security
- **Friction:** Large enterprises with extensive customer bases face a trust operations bottleneck where manual security questionnaire responses and document distribution create a sales cycle drag that scales poorly. 'Before Vanta, we used to manually distribute about 8,000 reports annually through secure file sharing. It caused delays, added overhead, and resulted in growing frustration.' Legacy trust workflows require trust teams to manually gather documentation, encrypt files, email responses, and handle follow-up questions — making them the bottleneck in every sales cycle while 12,000+ customers need access to security posture data.
- **Source:** https://www.vanta.com/customers/snowflake
- **Severity:** High. Named exec: Josh McKibben (Senior Director of Enterprise Security Compliance & Risk, Snowflake). Quantified: 2,000+ hours saved per year (1,000+ hours within the first eight months of launch); 2,000-3,000 hours annually spent on documentation distribution alone; 8,000+ complex manual requests annually; deployed in just two months; serves 12,000+ customers globally. Quotes: 'We needed a self-service portal that would quickly enable customers to get what they want and need, and reduce the human intervention on our side.' 'By using Vanta, we can repurpose and reapply our trust team's talents to other activities.'
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 140 and 141 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Security","Specific_Friction":"Enterprise companies managing multiple compliance frameworks and large vendor portfolios face a GRC operational ceiling where manual evidence collection, fragmented controls, and disconnected systems create an unsustainable burden. 'Samsara's GRC team was responsible for maintaining compliance across 10 frameworks, managing a portfolio of more than 600 vendors, and supporting security reviews at every stage of the sales cycle. With 820+ controls across frameworks and ~130 vendor reviews per month, the team was nearing an operational ceiling.' Without a unified platform, trust teams spend hours manually stitching together audit evidence while security reviews bottleneck revenue-critical sales cycles.","Source_URL":"https://www.vanta.com/customers/samsara","Severity_Impact":"High. Named exec: Nick Hardy (Senior Director of Security, GRC & PM, Samsara). Quantified: 820 controls → 260 (68% reduction); 1,200 evidence items mapped; SME interview time 70→40 hours (43% reduction); up to 50% faster vendor reviews; $150M+ influenced revenue; $300K+ ROI year one; ~130 vendor reviews/month."}
{"Pain_Point_Category":"Security","Specific_Friction":"Large enterprises with extensive customer bases face a trust operations bottleneck where manual security questionnaire responses and document distribution create a sales cycle drag that scales poorly. 'Before Vanta, we used to manually distribute about 8,000 reports annually through secure file sharing. It caused delays, added overhead, and resulted in growing frustration.' Legacy trust workflows require trust teams to manually gather documentation, encrypt files, email responses, and handle follow-up questions — making them the bottleneck in every sales cycle.","Source_URL":"https://www.vanta.com/customers/snowflake","Severity_Impact":"High. Named exec: Josh McKibben (Senior Director of Enterprise Security Compliance & Risk, Snowflake). Quantified: 2,000+ hours saved/year; 2,000-3,000 hours annually on documentation; 8,000+ manual requests; deployed in 2 months; serves 12,000+ customers."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 140 and 141 to jsonl');