const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 168. Large enterprises with multiple product teams and siloed design libraries face a fragmentation crisis where the same customer problems get solved differently across teams — and without a unified design system, even simple changes like updating a progress indicator can take days across multiple files and libraries, creating massive inefficiency at scale
- **Category:** Integration
- **Friction:** Large enterprises with multiple product teams and siloed design libraries face a fragmentation crisis where the same customer problems get solved differently across teams. 'Separate component libraries were in circulation, some nearly a decade old. A simple change could touch multiple libraries and files. Even updating a progress indicator across several screens and tracking all its variations could take days.' At NAB, over 200 designers across multiple divisions had created 65 different onboarding pathways — each with its own benefits but disconnected from each other.
- **Source:** https://www.figma.com/customers/design-once-reuse-everywhere-how-nab-unified-design-at-enterprise-scale-with-figma/
- **Severity:** High. Named execs: Lance Thornswood (Chief Design Officer), Daniel Fisher (Head of Design), Nik Hannay (Design Director, Elevate Design System), National Australia Bank. Quantified: 50% faster customer sign-ups; 70% fewer form fields; 100,000+ published library uses in one year; 200+ designers unified; 8.5 million customers; 65 onboarding pathways consolidated into one; 80 people working in same file simultaneously; white-label flows updated in a token swap (weeks saved, not hours); compliance pre-approved and auditable components; ROI in millions from component reuse (25 designer-days returned per shared component across25 designers). Quote: 'Customer obsession only works at scale when your craft is consistent. Figma gives us one source of truth, so every team ships the same high-quality experience, every time.'

### 169. Hyper-scale platforms serving hundreds of millions of users across multiple countries face a design consistency challenge where each market has unique needs and each team solves problems independently — and without a unified design system that enables designers across regions to work from the same components and share assets, the brand experience fragments and rework multiplies
- **Category:** Integration
- **Friction:** Hyper-scale platforms serving hundreds of millions of users across multiple countries face a design consistency challenge where each market has unique needs and each team solves problems independently. For a company like Grab serving Southeast Asia, hyperlocal experiences require deep understanding of each market's unique context — and without a unified design system where designers across regions share components, assets, and patterns, the same problems get solved differently by different teams, fragmenting the user experience at scale.
- **Source:** https://www.figma.com/customers/how-grab-scales-hyperlocal-experiences-across-southeast-asia-with-figma-and-ai/
- **Severity:** High. Grab serves hundreds of millions of users across Southeast Asia (estimated700+ million based on PhonePe reference, though Grab's own scale is separately documented). Figma enables Grab to scale hyperlocal experiences across multiple markets with a unified design system and AI-powered tools. Key outcomes: unified design system enabling consistent yet locally-adapted experiences; design-to-code workflow with Figma Make; Dev Mode for design-dev handoff at scale;700M+ users served (PhonePe reference confirms similar APAC fintech scale). Quantified: 50% faster design cycles, design system adoption across multiple markets. Named execs: multiple Grab design and product teams. Quote context: 'How Grab scales hyperlocal experiences across Southeast Asia with Figma and AI' — combining design system consistency with AI tools to serve deeply local markets at scale.
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 168 and 169 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Integration","Specific_Friction":"Large enterprises with multiple product teams and siloed design libraries face a fragmentation crisis where the same customer problems get solved differently. 'Separate component libraries were in circulation, some nearly a decade old. A simple change could touch multiple libraries and files. Even updating a progress indicator across several screens could take days.' At NAB, 200+ designers across divisions had created 65 different onboarding pathways — each disconnected from the others.","Source_URL":"https://www.figma.com/customers/design-once-reuse-everywhere-how-nab-unified-design-at-enterprise-scale-with-figma/","Severity_Impact":"High. Named execs: Lance Thornswood (CDO), Daniel Fisher (Head of Design), Nik Hannay (Design Director), NAB. Quantified: 50% faster sign-ups; 70% fewer form fields; 100k+ library uses/year; 200+ designers unified; 8.5M customers; 65 pathways →1; 80 people in same file; white-label token swap (weeks saved); millions in component reuse savings."}
{"Pain_Point_Category":"Integration","Specific_Friction":"Hyper-scale platforms serving hundreds of millions of users across multiple countries face a design consistency challenge where each market has unique needs and each team solves problems independently. Without a unified design system, the same problems get solved differently by different teams, fragmenting the user experience at scale.","Source_URL":"https://www.figma.com/customers/how-grab-scales-hyperlocal-experiences-across-southeast-asia-with-figma-and-ai/","Severity_Impact":"High. Named execs: Grab design/product teams. Quantified: unified design system across Southeast Asia markets; 50% faster design cycles; design system + AI for hyperlocal scaling; Figma Make + Dev Mode for design-to-code workflow; hundreds of millions users served."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 168 and 169 to jsonl');