const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 150. Large pharmaceutical companies with aggressive drug development timelines face a manual administrative bottleneck where scientists spend significant time on repetitive tasks like laboratory supply ordering — and without workflow automation, the time lost compounds across every researcher, every day, across millions of essential materials
- **Category:** Onboarding
- **Friction:** Large pharmaceutical companies with aggressive drug development timelines face a manual administrative bottleneck where scientists spend significant time on repetitive tasks like laboratory supply ordering. 'Bringing just one new medication to market can require millions of test tubes during the development phases. AstraZeneca discovered that employees were handwriting supply orders in a notebook, a process that took up to 30 minutes each time.' With 60,000+ requests flowing through manual processes annually, and scientists whose time is worth hundreds of dollars per hour being consumed by administrative work, the compounding cost is measured not just in dollars but in delayed medicines for patients who need them.
- **Source:** https://www.servicenow.com/customers/astrazeneca.html
- **Severity:** High. Named execs: Cindy Hoots (Chief Digital Officer and CIO, AstraZeneca), Dinesh Krishnan (Global Head of Enterprise Platforms, AstraZeneca), Jackie Crockford (VP of Global Business Services, AstraZeneca). Quantified: 30,000 hours/year cumulative time saved (supply ordering alone); 60,000+ requests/year across 400+ categories flowing through ServiceNow; managers spending 50+ hours onboarding employees, automating 10% saves 90,000+ hours; goal: 20 new medicines by 2030. Quote: 'Given the boldness of our ambition, IT and the use of technology are critical to achieving these results. At AstraZeneca, Every Minute Matters, because it's crucial that we get lifesaving medicines to patients as quickly as possible.'

### 151. Scaling service businesses with fragmented support channels face an operational ceiling where high-touch customer experience requires manual effort that doesn't scale — and without an AI agent that can handle phone, chat, and email uniformly, the choice is between hiring hundreds more people or accepting inconsistent, slow support that damages brand reputation
- **Category:** Integration
- **Friction:** Scaling service businesses with fragmented support channels face an operational ceiling where high-touch customer experience requires manual effort that doesn't scale. 'Clients might reach out to us through phone, email, chat or through social and get a slightly different experience each time. It was inefficient for us and frustrating for them.' With 160+ studios and 30-40 new locations opening annually, support volume grew to tens of thousands of conversations per month, studio staff were pulled from their primary roles to field admin questions, and clients waited more than a day for basic answers — creating a service experience that didn't match the premium brand promise.
- **Source:** https://fin.ai/customers/solidcore
- **Severity:** High. Named exec: Shane McCarthy (Chief Digital Officer, solidcore). Quantified: $569,000 in annual savings; >12,000 hours saved annually; 80% Fin CSAT and 93% human CSAT; 23% of inbound calls fully resolved by Fin; nearly 50% of targeted workflow conversations resolved by Fin; First Response Time reduced by over a day in some channels; 160 studios, opening 30-40 more per year. Quote: 'If we kept growing with our old setup, we'd have to hire hundreds more people. That just wasn't feasible. We needed a unified system that could scale with us, deliver a consistent experience, and take some of the pressure off our studio teams.'
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 150 and 151 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Onboarding","Specific_Friction":"Large pharmaceutical companies with aggressive drug development timelines face a manual administrative bottleneck where scientists spend significant time on repetitive tasks like laboratory supply ordering. 'Bringing just one new medication to market can require millions of test tubes during the development phases. AstraZeneca discovered that employees were handwriting supply orders in a notebook, a process that took up to 30 minutes each time.' With 60,000+ requests flowing through manual processes annually, and scientists whose time is worth hundreds of dollars per hour being consumed by administrative work, the compounding cost is measured not just in dollars but in delayed medicines for patients who need them.","Source_URL":"https://www.servicenow.com/customers/astrazeneca.html","Severity_Impact":"High. Named execs: Cindy Hoots (CDO/CIO, AstraZeneca), Dinesh Krishnan (Global Head of Enterprise Platforms), Jackie Crockford (VP Global Business Services). Quantified: 30,000 hours/year saved; 60,000+ requests/year across 400+ categories; managers spending 50+ hrs onboarding, automating 10% saves 90,000+ hours; goal: 20 new medicines by 2030."}
{"Pain_Point_Category":"Integration","Specific_Friction":"Scaling service businesses with fragmented support channels face an operational ceiling where high-touch customer experience requires manual effort that doesn't scale. 'Clients might reach out to us through phone, email, chat or through social and get a slightly different experience each time. It was inefficient for us and frustrating for them.' With 160+ studios and 30-40 new locations opening annually, support volume grew to tens of thousands of conversations per month, studio staff were pulled from their primary roles to field admin questions, and clients waited more than a day for basic answers — creating a service experience that didn't match the premium brand promise.","Source_URL":"https://fin.ai/customers/solidcore","Severity_Impact":"High. Named exec: Shane McCarthy (Chief Digital Officer, solidcore). Quantified: $569k annual savings; 12,000+ hours/year saved; 80% Fin CSAT and 93% human CSAT; 23% of inbound calls fully resolved by Fin; nearly 50% of workflow conversations resolved by Fin; First Response Time reduced by over a day; 160 studios, opening 30-40 more per year."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 150 and 151 to jsonl');