const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 146. Enterprise technology companies with large product portfolios face a cross-sell and upsell blindness problem where without a unified view of customer product usage, sales and marketing teams cannot identify the right "next best offer" for each account — resulting in revenue leakage as customers underutilize the platform while sales teams lack signals to trigger expansion conversations
- **Category:** Integration
- **Friction:** Enterprise technology companies with large product portfolios face a cross-sell and upsell blindness problem where without a unified view of customer product usage, sales and marketing teams cannot identify the right 'next best offer' for each account. 'With hundreds of products spanning thousands of customers, IBM has a lot to offer, but not all customers are aware of the solutions they can provide. There was no single source of data which could be used to monitor the end-to-end customer funnel.' Without a customer data platform that maps product usage to accounts, revenue teams are flying blind — unable to proactively trigger expansion conversations at the right account with the right product at the right time.
- **Source:** https://customers.twilio.com/en-us/ibm
- **Severity:** High. Named execs: Nic Sauriol (Software Development Leader, IBM Cloud Platform), Peter Ikladious (Director of Growth and User Engagement, IBM). Quantified: 70% increase in Cloud revenue over a 3-month test period; 30% improvement in product adoption; 17% increase in billable usage; 250 point improvement in downloaded software trial engagement; Over $2M saved by one product-engineering team; 10X return on Twilio Segment investment; standardized data across 150 products. Quote: 'With real-time integrated data flows, we can truly understand what people are doing with our platform. It doesn't matter where you look at the data, with Segment, it's always consistent.'

### 147. Scaling organizations face a data activation bottleneck where audience creation requires manual wrangling across multiple systems, engineering teams maintain parallel data pipelines, and marketing teams wait days for audience builds — and without a composable CDP architecture, the choice is between slow, manual processes that limit experimentation or expensive point-to-point integrations that don't scale
- **Category:** Integration
- **Friction:** Scaling organizations face a data activation bottleneck where audience creation requires manual wrangling across multiple systems, engineering teams maintain parallel data pipelines, and marketing teams wait days for audience builds. 'Identifying high-value user cohorts for outreach required pulling data from multiple systems–including customer relationship management tools, product usage analytics, and internal spreadsheets–then manually stitching them into static lists. This process could take 9-10 hours each quarter.' Without a composable CDP architecture that unifies data and enables self-serve audience creation, marketing and CS teams are bottlenecked by analytics team turnaround times, limiting experimentation speed and real-time responsiveness.
- **Source:** https://customers.twilio.com/en-us/asana
- **Severity:** High. Named execs: Grace Liu (Product Owner for the CDP, Asana), Amrutha Suresh (Head of Martech and Enterprise AI, Asana), Sai Kesavamatam (Data Architect, Asana). Quantified: 250+ working days saved through audiences built in Segment (in just over a year); marketing and CS went from 2-day wait times to same-day execution; up to 57% increase in web leads through paid media campaigns; 48% boost in Academy course engagement; 4% CS email-to-meeting conversion rate. Quote: 'We saw an opportunity to move away from point-to-point integrations and toward a composable architecture that could scale across teams.'
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 146 and 147 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Integration","Specific_Friction":"Enterprise technology companies with large product portfolios face a cross-sell and upsell blindness problem where without a unified view of customer product usage, sales and marketing teams cannot identify the right 'next best offer' for each account. 'With hundreds of products spanning thousands of customers, IBM has a lot to offer, but not all customers are aware of the solutions they can provide. There was no single source of data which could be used to monitor the end-to-end customer funnel.' Without a customer data platform that maps product usage to accounts, revenue teams are flying blind.","Source_URL":"https://customers.twilio.com/en-us/ibm","Severity_Impact":"High. Named execs: Nic Sauriol (Software Development Leader, IBM Cloud), Peter Ikladious (Director of Growth & User Engagement, IBM). Quantified: 70% increase in Cloud revenue over 3 months; 30% improvement in product adoption; 17% increase in billable usage; Over $2M saved by one product-engineering team; 10X return on Segment investment; standardized data across 150 products."}
{"Pain_Point_Category":"Integration","Specific_Friction":"Scaling organizations face a data activation bottleneck where audience creation requires manual wrangling across multiple systems, engineering teams maintain parallel data pipelines, and marketing teams wait days for audience builds. 'Identifying high-value user cohorts for outreach required pulling data from multiple systems–including customer relationship management tools, product usage analytics, and internal spreadsheets–then manually stitching them into static lists. This process could take 9-10 hours each quarter.' Without a composable CDP architecture, marketing and CS are bottlenecked by analytics team turnaround times, limiting experimentation speed.","Source_URL":"https://customers.twilio.com/en-us/asana","Severity_Impact":"High. Named execs: Grace Liu (Product Owner for the CDP, Asana), Amrutha Suresh (Head of Martech and Enterprise AI, Asana). Quantified: 250+ working days saved in just over a year; marketing/CS from 2-day wait to same-day execution; 57% increase in web leads; 48% boost in Academy course engagement; 4% CS email-to-meeting conversion rate."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 146 and 147 to jsonl');