const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 154. Enterprise companies with fragmented tech stacks from years of acquisitions face a support automation challenge where multiple Salesforce instances, overlapping ERPs, and siloed knowledge bases make AI integration seem daunting — and without an AI agent that works with existing complexity rather than requiring a full rebuild, the choice is between expensive greenfield projects or accepting that support will never scale
- **Category:** Integration
- **Friction:** Enterprise companies with fragmented tech stacks from years of acquisitions face a support automation challenge where multiple Salesforce instances, overlapping ERPs, and siloed knowledge bases make AI integration seem daunting. 'Years of mergers and acquisitions had left a multitude of systems: numerous Salesforce instances, overlapping ERPs, and siloed data. Automating across such a fragmented environment felt daunting.' With 145,000 retail and restaurant locations across 100+ countries, tens of thousands of monthly support requests, and complex tech stacks in constant use, the only path to scale is AI that works with existing systems — not replacing them.
- **Source:** https://fin.ai/customers/lightspeed-transformation
- **Severity:** High. Named exec: Yamine Gluchow (VP of Information Systems, Lightspeed). Quantified: 43,000+ Fin resolutions per month; 88% Fin involvement rate; 72% Fin resolution rate; 12+ languages; 100+ countries; ~145,000 retail/restaurant locations; started at 20% resolution → now 72%; went live in weeks; complex stack with multiple Salesforce instances, overlapping ERPs, legacy tools. Quote: 'We didn\'t have to untangle everything, Fin worked with our complexity, not in spite of it.'

### 155. High-volume subscription and financial services platforms face a manual triage bottleneck where button-based routing flows place the burden of precision on customers, and misrouted conversations create hours of daily manual work for support teams — and without an AI agent that can interpret intent and handle complexity, support teams spend their days fixing routing errors instead of solving problems
- **Category:** Integration
- **Friction:** High-volume subscription and financial services platforms face a manual triage bottleneck where button-based routing flows place the burden of precision on customers, and misrouted conversations create hours of daily manual work for support teams. 'At the peak of the problem, one teammate was spending two to three hours a day manually rerouting conversations. The work mattered, but it wasn't sustainable.' With 60,000+ monthly conversations and sensitive financial data at stake, manual triage is not just inefficient — it creates risk of errors in a domain where precision matters.
- **Source:** https://fin.ai/customers/rocket-money
- **Severity:** High. Named exec: Michelle McGowan (Director of Operations, Rocket Money). Quantified: ~$1M annual ROI from Fin; 68% Fin resolution rate; 54% Fin involvement rate; 60,000+ conversations/month; human CSAT increased by 6 points; email-based billing management: 80%+ CSAT; manual triage eliminated; average handle times dropped; new AI-focused roles emerging. Quote: 'This is what a modern support team looks like. It's not about removing humans. It's about redesigning the work so humans are focused where they add the most value.'
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 154 and 155 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = `{"Pain_Point_Category":"Integration","Specific_Friction":"Enterprise companies with fragmented tech stacks from years of acquisitions face a support automation challenge where multiple Salesforce instances, overlapping ERPs, and siloed knowledge bases make AI integration seem daunting. 'Years of mergers and acquisitions had left a multitude of systems: numerous Salesforce instances, overlapping ERPs, and siloed data. Automating across such a fragmented environment felt daunting.' With 145,000 retail and restaurant locations across 100+ countries, tens of thousands of monthly support requests, and complex tech stacks in constant use, the only path to scale is AI that works with existing systems — not replacing them.","Source_URL":"https://fin.ai/customers/lightspeed-transformation","Severity_Impact":"High. Named exec: Yamine Gluchow (VP of Information Systems, Lightspeed). Quantified: 43,000+ Fin resolutions/month; 88% Fin involvement rate; 72% Fin resolution rate; 12+ languages; 100+ countries; ~145,000 locations; started at 20% → now 72%; went live in weeks."}
{"Pain_Point_Category":"Integration","Specific_Friction":"High-volume subscription and financial services platforms face a manual triage bottleneck where button-based routing flows place the burden of precision on customers, and misrouted conversations create hours of daily manual work for support teams. 'At the peak of the problem, one teammate was spending two to three hours a day manually rerouting conversations.' With 60,000+ monthly conversations and sensitive financial data at stake, manual triage is not just inefficient — it creates risk of errors in a domain where precision matters.","Source_URL":"https://fin.ai/customers/rocket-money","Severity_Impact":"High. Named exec: Michelle McGowan (Director of Operations, Rocket Money). Quantified: ~$1M annual ROI from Fin; 68% Fin resolution rate; 54% Fin involvement rate; 60,000+ conversations/month; human CSAT +6 points; 80%+ CSAT on email billing; manual triage eliminated; average handle times dropped."}`;

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.split('\n').join('\n') + '\n');
console.log('Appended findings 154 and 155 to jsonl');