const fs = require('fs');

const memPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\MEMORY.md';
let memData = fs.readFileSync(memPath, 'utf8');

const newFindings = `
### 170. Global manufacturers with massive multi-country footprints face a fragmented-systems crisis where product-level environmental compliance reporting is impossible because each local business unit chose its own tools, and without a centralized integration layer, the company cannot prove batch-level carbon emissions, recyclability, or water consumption to regulators
- **Category:** Integration
- **Friction:** Global manufacturers operating across 70+ countries face a fragmented-systems crisis where local business units each chose their own tools, creating silos that block compliance reporting. "We need to prove compliance with environmental regulations, such as demonstrating product-per-product CO2 emission levels, recyclability, and water consumption. To achieve this, we need complete traceability down to the batch production level. We know in some products we have recyclable rates above 80%, but it is not enough to know that you're doing right, you need proof." Outdated point-to-point integrations blocked real-time visibility.
- **Source:** https://www.mulesoft.com/case-studies/saint-gobain-manufacturing
- **Severity:** High. Named exec: Bertrand Cernesson (EMEA CIO, Saint-Gobain). Quantified: €46.5B revenue; 160,000 employees across 76 countries; 90 workflows deployed in 6 months; API reusability 35% → 57% (and rising); SAP S/4HANA migration target 2029; 1/3 of group revenue in France+Germany phase 2; real-time ERP-to-shop-floor SCADA integration; carbon footprint + recyclability proof at batch level.

### 171. Telecom giants operating wireline + mobility businesses face a dual-system service crisis where customers had to repeat their issue across siloed legacy systems, and without a unified API layer the support agents could not see the customer's full inventory of services, leading to fragmented experiences and slow resolution at scale
- **Category:** Integration
- **Friction:** Telecom giants operating multiple service lines face a dual-system service crisis where customers had to repeat their issue across siloed legacy systems. "The problem we had with customer service calls was there was no easy way for our service teams to access the wealth of historical data." Separate systems existed for wireline vs. mobility, multiple teams were independently building the same APIs, and finding the right API was hard — creating duplication of effort and complexity that grew with the API surface area.
- **Source:** https://www.mulesoft.com/case-studies/att
- **Severity:** High. Named exec: Brad Ringer (Principal Solution Engineer, AT&T). Quantified: $125B business; 120M mobility subscribers; 10M+ fiber subscribers; 9,000 support agents; 240 million API calls per day; hundreds of retail stores; production support calls "virtually stopped" after unification; multiple teams building the same API consolidated; AI agentic future planned.

### 172. Global tech hardware companies shifting to software-led models face a three-BU silo problem where distinct product lines and international operations each carried their own architecture, and without a common integration layer enabling reusable API building blocks, agentic AI cannot safely scale across business units
- **Category:** Integration
- **Friction:** Global tech hardware companies shifting to software-led, agentic models face a multi-BU silo problem where three distinct business units and international operations each carried their own architecture, scattering product expertise and workplace know-how. "The next phase of our growth will see us move from apps and systems to AI agents." Point-to-point integrations were slow and manual; without centralized governance, AI agents could not be safely orchestrated across HR, Sales, Service, and Finance.
- **Source:** https://www.mulesoft.com/case-studies/barco-tech
- **Severity:** High. Named execs: Philippe Verlinde (Chief Digital and Information Officer), Joris Diependaele (Senior Integration Architect), Barco. Quantified: €1B revenue; 3,300 employees supported by agents; 5 cross-agent ecosystems connected and orchestrated; 100% API compliance; Barco Genius AI assistant built from headless agents via A2A; reusable composable building blocks; integration time reduced; shadow IT limited by pre-approved assets.

### 173. Workforce-tech startups orchestrating thousands of AI agents face a "build vs. orchestrate" trap where building the orchestration layer in-house would consume 15+ months of engineering capacity, and without an enterprise-grade agent fabric they cannot safely connect to customers' SAP, Workday, and Salesforce systems
- **Category:** Integration
- **Friction:** Workforce-tech startups orchestrating thousands of AI agents face a "build vs. orchestrate" trap — building the orchestration layer in-house would consume 15+ months of engineering capacity and pull focus from the agents that deliver customer value. Connecting securely to enterprise customers' systems (SAP, Workday, Salesforce) required an enterprise-grade, pre-built agent fabric with secure gateway, agent registry, and observability — none of which a small product team can ship at parity.
- **Source:** https://www.mulesoft.com/case-studies/rpotential
- **Severity:** High. Named execs: Ron Chaney (CTO), Greg Shewmaker (CEO), r.Potential (Adecco Group spin-off). Quantified: 1,900 largest enterprises analyzed; 100M employees; $12.5T in unlocked potential claimed; 15 months developer time saved by offloading orchestration; 1,000+ agents orchestrated at scale; live data ingestion from first 3 enterprise customers; A2A + MCP; private cloud deployment with Omni Gateway.

### 174. Global conglomerates with continuous M&A activity face a 6-month identity-integration crisis where each acquired company runs its own IT environment, and forcing a tool replacement is too costly — so the parent needs a vendor-neutral identity layer that can link disparate identity platforms in 1-3 months instead of 6 months of on-premise network re-wiring
- **Category:** Integration
- **Friction:** Global conglomerates with continuous M&A activity face a 6-month identity-integration crisis where each acquired company runs its own IT environment. "Until a few years ago, it was realistic for some M&A companies to replace their IT environment to match ours, but as the scale of acquisitions has increased... there are more cases where the IT environment is at the same maturity as ours resulting in a complex process." Forcing acquired companies to switch tools is too costly, and the on-premise identity-integration approach alone was too slow.
- **Source:** https://www.okta.com/customers/hitachi/
- **Severity:** High. Named execs: Hitoshi Tanaka (GM, Global Solutions 2nd Office, IT Strategy & Digital Integration Division) and Ono (same division), Hitachi. Quantified: ~480,000 identities managed; ~100 AD authentication servers consolidated; identity integration time 1-3 months (cloud) vs. 6 months (on-premise); 41 tons CO2/year reduction; hub-and-spoke model planned for global M&A scale; MFA + Device Trust + passwordless FastPass; OIG for governance.

### 175. Global sports franchises with 50+ brand partners face a manual user-provisioning crisis where each partner-portal access request required McLaren staff to create the account, and doubling active partner users from 500 to 1,000 was impossible without automated, scalable, secure identity management
- **Category:** Onboarding & Deployment
- **Friction:** Global sports franchises with 50+ brand partners face a manual user-provisioning crisis where each partner-portal access request required staff to create accounts manually. "Partners need fast, secure, frictionless access to this portal so they can achieve their goals efficiently. However, to access the portal, partners previously had to contact the McLaren team, who managed user profiles manually." Doubling active partner users from 500 → 1,000 was not possible without automated onboarding/offboarding and SSO at consumer-grade scale (millions of fans during race peaks).
- **Source:** https://www.okta.com/customers/mclaren/
- **Severity:** High. Named entity: McLaren Racing (F1: 200+ Grand Prix wins, 13 Drivers' World Championships). Quantified: 50+ brand partners; active partner users goal 500 → 1,000 (100% growth); only 1% of F1 fans will ever attend a physical race, so digital scale dominates; Auth0 chosen for global reach + traffic-spike scalability; F1 sport experiencing rapid global growth; frictionless web + mobile SSO required; automatic offboarding of inactive users for compliance.

### 176. Hyper-growth SaaS companies in regulated industries (T&E, payments, PII) face an in-house-IAM ceiling where their homegrown customer identity solution cannot keep up with identity-based attacks at scale, and they need a vendor-neutral identity layer that lets them centralize workforce + customer identity into one data set
- **Category:** Security and Governance
- **Friction:** Hyper-growth SaaS companies in regulated industries (T&E, payments, PII) face an in-house-IAM ceiling where their homegrown customer identity solution cannot keep up with identity-based attacks. "Because Navan collects payment information, personal identifying information (PII), and other sensitive data, its in-house customer identity and access management (IAM) solution soon proved inadequate." With identity-based attacks increasing and zero-trust mandates maturing, the only path is to consolidate customer + workforce identity into one centralized data set for faster threat resolution.
- **Source:** https://www.okta.com/customers/navan/
- **Severity:** High. Named execs: Kim Huffman (CIO), Chris Price (Head of Business Technology), Prabhath Karanth (Head of Customer Trust and Security), Kelly Soderlund (Sr. Director of Corporate Communications), Navan. Quantified: 2,900+ employees across 40 markets; Okta Workforce since 2019 + Auth0 added 3 years later; rapid hypergrowth phase; high mix of "highly regulated customers" with strict requirements vs. customers with higher risk tolerance; Auth0 Organizations feature for per-customer IAM branding; zero-trust + stack defense strategy.

### 177. Global logistics enterprises with on-prem data warehouses face a reporting-system reliability crisis where BI tools crash if run for more than a month of data, and business analysts depend on other departments to build reports — blocking leadership from accessible, company-wide visibility and stopping data-science teams from launching gen-AI projects
- **Category:** Integration
- **Friction:** Global logistics enterprises with on-prem data warehouses (SQL server, mainframe) face a reporting-system reliability crisis. "Reporting processes didn't provide leadership with accessible visibility across the organization, while business analysts relied on other departments to create business intelligence reports. The reporting tool was limited to running in one or two locations using just a month's worth of data — and would crash if used for extended periods." This blocks company-wide leadership visibility and prevents the data-science team from launching gen-AI projects that require enterprise-scale, governed data.
- **Source:** https://www.snowflake.com/en/customers/all-customers/case-study/penske/
- **Severity:** High. Named exec: Vishwa Ram (VP, Data Science and Analytics, Penske Logistics). Quantified: BI reports built with 5 years of data in 15 minutes (vs. crashes on 1 month on-prem); Tableau self-service certified tools; nearly 30 data columns per associate dashboard manually parsed; Cortex AI for LLM-driven insights inside governed Snowflake perimeter; Document AI planned for handwritten logbooks; Snowflake as recruiting incentive for data scientists.
`;

fs.writeFileSync(memPath, memData + newFindings);
console.log('Appended findings 170-177 to MEMORY.md');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = [
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Global manufacturers operating across 70+ countries face a fragmented-systems crisis where local business units each chose their own tools, creating silos that block compliance reporting. Need complete traceability down to batch production level for product-level CO2, recyclability, water consumption. Outdated point-to-point integrations block real-time visibility.","Source_URL":"https://www.mulesoft.com/case-studies/saint-gobain-manufacturing","Severity_Impact":"High. Named exec: Bertrand Cernesson (EMEA CIO, Saint-Gobain). Quantified: €46.5B revenue; 160,000 employees across 76 countries; 90 workflows deployed in 6 months; API reusability 35% → 57%; SAP S/4HANA migration target 2029; real-time ERP-to-shop-floor SCADA integration; carbon footprint + recyclability proof at batch level."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Telecom giants operating wireline + mobility face a dual-system service crisis where customers had to repeat their issue across siloed legacy systems. Multiple teams were independently building the same APIs, finding the right API was hard, creating duplication of effort and growing complexity.","Source_URL":"https://www.mulesoft.com/case-studies/att","Severity_Impact":"High. Named exec: Brad Ringer (Principal Solution Engineer, AT&T). Quantified: $125B business; 120M mobility subscribers; 10M+ fiber subscribers; 9,000 support agents; 240 million API calls per day; hundreds of retail stores; production support calls virtually stopped after unification; AI agentic future planned."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Global tech hardware companies shifting to software-led, agentic models face a multi-BU silo problem where distinct product lines and international operations each carry their own architecture. Point-to-point integrations are slow and manual; without centralized governance, AI agents cannot be safely orchestrated across HR, Sales, Service, Finance.","Source_URL":"https://www.mulesoft.com/case-studies/barco-tech","Severity_Impact":"High. Named execs: Philippe Verlinde (CDIO), Joris Diependaele (Senior Integration Architect), Barco. Quantified: €1B revenue; 3,300 employees supported by agents; 5 cross-agent ecosystems connected and orchestrated; 100% API compliance; Barco Genius AI assistant built from headless agents via A2A; reusable composable building blocks."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Workforce-tech startups orchestrating thousands of AI agents face a build-vs-orchestrate trap — building the orchestration layer in-house would consume 15+ months of engineering capacity and pull focus from the agents that deliver customer value. Connecting securely to enterprise customers SAP, Workday, Salesforce requires an enterprise-grade pre-built agent fabric with secure gateway, registry, and observability.","Source_URL":"https://www.mulesoft.com/case-studies/rpotential","Severity_Impact":"High. Named execs: Ron Chaney (CTO), Greg Shewmaker (CEO), r.Potential (Adecco Group spin-off). Quantified: 1,900 largest enterprises analyzed; 100M employees; $12.5T unlocked potential claimed; 15 months developer time saved; 1,000+ agents orchestrated; live data ingestion from first 3 enterprise customers."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Global conglomerates with continuous M&A activity face a 6-month identity-integration crisis where each acquired company runs its own IT environment. Forcing acquired companies to switch tools is too costly; the on-premise identity-integration approach alone is too slow — they need a vendor-neutral identity layer that can link disparate identity platforms in 1-3 months.","Source_URL":"https://www.okta.com/customers/hitachi/","Severity_Impact":"High. Named execs: Hitoshi Tanaka (GM, IT Strategy & Digital Integration Division), Ono (same division), Hitachi. Quantified: ~480,000 identities managed; ~100 AD servers consolidated; identity integration 1-3 months (cloud) vs. 6 months (on-prem); 41 tons CO2/year reduction; hub-and-spoke model planned for global M&A."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Global sports franchises with 50+ brand partners face a manual user-provisioning crisis where each partner-portal access request required staff to create accounts manually. Doubling active partner users 500 → 1,000 was not possible without automated onboarding/offboarding and SSO at consumer-grade scale (millions of fans during race peaks).","Source_URL":"https://www.okta.com/customers/mclaren/","Severity_Impact":"High. Named entity: McLaren Racing (F1: 200+ Grand Prix wins, 13 Drivers World Championships). Quantified: 50+ brand partners; 500 → 1,000 partner users (100% growth); only 1% of F1 fans attend physical races; Auth0 chosen for global reach + traffic-spike scalability; frictionless web + mobile SSO required."}',
  '{"Pain_Point_Category":"Security and Governance","Specific_Friction":"Hyper-growth SaaS companies in regulated industries (T&E, payments, PII) face an in-house-IAM ceiling where their homegrown customer identity solution cannot keep up with identity-based attacks. Need to consolidate customer + workforce identity into one centralized data set for faster threat resolution and zero-trust posture.","Source_URL":"https://www.okta.com/customers/navan/","Severity_Impact":"High. Named execs: Kim Huffman (CIO), Chris Price (Head of Business Technology), Prabhath Karanth (Head of Customer Trust and Security), Kelly Soderlund (Sr. Director of Corporate Communications), Navan. Quantified: 2,900+ employees across 40 markets; Okta Workforce since 2019 + Auth0 added 3 years later; high mix of highly-regulated customers with strict requirements; zero-trust + stack defense."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Global logistics enterprises with on-prem data warehouses (SQL server, mainframe) face a reporting-system reliability crisis where BI tools crash if run for more than a month of data, and business analysts depend on other departments to build reports — blocking leadership from accessible company-wide visibility and stopping data-science teams from launching gen-AI projects.","Source_URL":"https://www.snowflake.com/en/customers/all-customers/case-study/penske/","Severity_Impact":"High. Named exec: Vishwa Ram (VP, Data Science and Analytics, Penske Logistics). Quantified: BI reports built with 5 years of data in 15 minutes (vs. crashes on 1 month on-prem); Tableau self-service certified tools; nearly 30 data columns per associate dashboard manually parsed; Cortex AI for LLM-driven insights inside governed Snowflake perimeter; Document AI planned."}'
];

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.join('\n') + '\n');
console.log('Appended 8 findings (170-177) to jsonl');
console.log('jsonl now: ' + (jsonlData.trim().split('\n').length + 8) + ' lines');
