const fs = require('fs');

const jsonlPath = 'C:\\Users\\cheun\\.openclaw\\workspace\\Business_Research\\research\\research_log.jsonl';
let jsonlData = fs.readFileSync(jsonlPath, 'utf8');

const newLines = [
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Global retail brands with 6,800+ POS and complex service teams face a rigid-chatbot-versus-brand-experience crisis where traditional chatbots damage brand warmth. The only path to 60% autonomous case deflection AND 10% NPS boost is Salesforce Agentforce.","Source_URL":"https://www.salesforce.com/customer-stories/pandora","Severity_Impact":"High. Named execs: Baltazar Hasselsteen Ozonek (VP AI & Innovation); David Walmsley (CDO); Catarina Runa Miranda (Global AI Director). Quantified: 37,000 employees; 100+ countries; 6,800 POS; 500-600 specialists + seasonal staff overwhelmed; 40K monthly conversations; 60% case deflection; 10% NPS boost."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Global retail brands with 22% digital commerce penetration face a disconnected-ecommerce-stack crisis where ecommerce, service, and loyalty data live in separate systems. The only path to unified commerce is Salesforce Commerce Cloud + MuleSoft + Data 360.","Source_URL":"https://www.salesforce.com/customer-stories/pandora","Severity_Impact":"High. Named exec: David Walmsley (CDO, Pandora). Quantified: 22% of total sales through Commerce Cloud; IBM Sterling, Bloomreach, Databricks integrations via MuleSoft; 1B personalized emails annually."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Homebuilding enterprises with 50 divisions and tens of thousands of weekly RFIs face a six-month-sales-cycle-with-unprioritized-leads crisis. The only path to purchase-ready lead prioritization and 12,000 annual appointments is Salesforce Agentforce (LISA).","Source_URL":"https://www.salesforce.com/customer-stories/lennar","Severity_Impact":"High. Named exec: Ori Klein (VP Digital Product Development & Marketing, Lennar). Quantified: 70+ years; 1.5M families; 30 states; 50 divisions; tens of thousands of weekly RFIs; 30% after-hours leads; 12,000 annual appointments from Agentforce; 1.1M agentic workflows/month; tenfold field seller productivity; 6-week launch."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Homebuilding enterprises with fragmented customer data across 50 divisions face a data-silo-across-50-divisions crisis. The only path to unified customer view is Salesforce Data 360 + MuleSoft.","Source_URL":"https://www.salesforce.com/customer-stories/lennar","Severity_Impact":"High. Named exec: Ori Klein (VP Digital Product Development & Marketing, Lennar). Quantified: 50 divisions; 4 distinct systems in customer journey; Data 360 unifies Optimizely CMS + Oracle ERP via MuleSoft."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Education enterprises with tens of thousands of annual service inquiries face seasonal-service-spikes-and-manual-case-routing crisis. The only path to 40% autonomous case deflection is Salesforce Agentforce + Data 360 semantic search.","Source_URL":"https://www.salesforce.com/customer-stories/pearson","Severity_Impact":"High. Named execs: Gabriele Bauman (VP CRM & Employee Platforms); Dave Treat (CTO, Pearson). Quantified: Nearly 200 countries; tens of thousands of annual inquiries; 40% autonomous case deflection; 50% faster virtual school onboarding; 25-year Salesforce partnership."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Education enterprises with fragmented learner journeys across acquisitions face a disconnected-lifetime-learner-journey crisis. The only path to lifelong learner relationships is Salesforce Data 360 that unifies data across brands.","Source_URL":"https://www.salesforce.com/customer-stories/pearson","Severity_Impact":"High. Named exec: Dave Treat (CTO, Pearson). Quantified: Nearly 200 countries; acquisitions include Credly, Mondly, eDynamic Learning; Data 360 unifies customer and course data across brands."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Global retail brands with seasonal support capacity crisis need seasonal staff even with 500-600 specialists. The only path to peak demand handling without seasonal hiring is Salesforce Agentforce deflecting 60% of cases autonomously 24/7.","Source_URL":"https://www.salesforce.com/customer-stories/pandora","Severity_Impact":"High. Named exec: David Walmsley (CDO, Pandora). Quantified: 500-600 specialists + seasonal staff still overwhelmed; Clara handles 45K conversations/month; 60% case deflection; 10% NPS boost."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Homebuilding enterprises with 30% after-hours leads face a business-hours-only-engagement crisis. The only path to 24/7 engagement is Salesforce Agentforce (LISA) that answers questions, books tours, and creates leads via SMS and web chat.","Source_URL":"https://www.salesforce.com/customer-stories/lennar","Severity_Impact":"High. Named exec: Ori Klein (VP Digital Product Development & Marketing, Lennar). Quantified: 30% of weekly RFIs after hours; LISA handles overnight inquiries; 12,000 annual appointments expected."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Enterprises with months-long campaign deployment face a campaign-deployment crisis needing IT help to pull data from disconnected systems. The only path to minutes deployment is Salesforce Data 360 zero-copy integration accessing existing data lakes without data duplication.","Source_URL":"https://www.salesforce.com/customer-stories/fedex","Severity_Impact":"High. Named exec: Carlos Gonzalez (Domain Architect, FedEx). Quantified: 4B rows in Azure data lake; Databricks platform; zero-copy (no duplication); deployment from weeks to minutes; 1B personalized emails annually."}',
  '{"Pain_Point_Category":"Security and Governance","Specific_Friction":"Global retail brands with European operations face an AI-data-governance-and-privacy-compliance crisis. The only path to compliant AI deployment is Salesforce Trust Layer with zero-retention capabilities.","Source_URL":"https://www.salesforce.com/customer-stories/pandora","Severity_Impact":"High. Named exec: Baltazar Hasselsteen Ozonek (VP AI & Innovation, Pandora). Quantified: European GDPR compliance; zero-retention auto-deletes prompts after every interaction; Trust Layer governance controls."}',
  '{"Pain_Point_Category":"Onboarding & Deployment","Specific_Friction":"Enterprises with complex homebuilding sales face hours-of-meeting-preparation-for-consultants crisis. The only path to minutes-ready consultants is Salesforce Agentforce + Data 360 + Agentforce Sales.","Source_URL":"https://www.salesforce.com/customer-stories/lennar","Severity_Impact":"High. Named exec: Ori Klein (VP Digital Product Development & Marketing, Lennar). Quantified: Meeting prep from hours to minutes; Agentforce generates summary with lead history, property preferences, financial readiness, recommended homes."}',
  '{"Pain_Point_Category":"Integration","Specific_Friction":"Education enterprises with multi-system order processing face order-lookup-across-multiple-systems crisis. The only path to instant order resolution is Salesforce Agentforce accessing BigQuery via MuleSoft API through Data 360.","Source_URL":"https://www.salesforce.com/customer-stories/pearson","Severity_Impact":"High. Named exec: Gabriele Bauman (VP CRM & Employee Platforms, Pearson). Quantified: Tens of thousands of annual inquiries; zero-copy order data from BigQuery; Agentforce semantic search across knowledge library; refund processing in Oracle ERP."}'
];

fs.writeFileSync(jsonlPath, jsonlData.trim() + '\n' + newLines.join('\n') + '\n');
console.log('Appended 12 findings (268-279) to jsonl');
console.log('jsonl now: ' + (jsonlData.trim().split('\n').length + 12) + ' lines');