const fs = require('fs');
const lines = [
  JSON.stringify({finding: 668, category: "Performance and Reliability", friction: "Kaizen Gaming (13M customers, real-time sports betting on Betano) faced 'real-time-latency-paradox' where routing global traffic (Brazil to Europe) resulted in high latency around one second and10-second delay could cause bet cancellation or rejection, directly impacting core business metrics", url: "https://www.cloudflare.com/case-studies/kaizen-gaming/", severity: "High", company: "Kaizen Gaming"}),
  JSON.stringify({finding: 669, category: "Performance and Reliability", friction: "Kaizen Gaming needed ~300 custom servers just for SignalR WebSocket connections (each pod handles ~2,000 connections, 600,000 concurrent clients at peak) - 'We had to be prepared for the worst, imagine if half of Brazil decides to log in at the same time, there's no room for autoscaling'", url: "https://www.cloudflare.com/case-studies/kaizen-gaming/", severity: "High", company: "Kaizen Gaming"}),
  JSON.stringify({finding: 670, category: "Security and Governance", friction: "Intility (650 customers, 50,000 users, 2,500 locations) faced 'multi-tenant-security-complexity' where hosting1000+ web applications for multiple clients across multiple verticals each with unique security and authentication requirements created mounting security challenges", url: "https://www.cloudflare.com/case-studies/intility/", severity: "High", company: "Intility"}),
  JSON.stringify({finding: 671, category: "Security and Governance", friction: "Intility faced 'VPN-maintenance-drain' where traditional VPN model required maintaining multiple VPN concentrators for each customer across data centers demanding constant patching and scaling - administrative burdens distracted SOC and engineering teams from strategic product development", url: "https://www.cloudflare.com/case-studies/intility/", severity: "High", company: "Intility"}),
  JSON.stringify({finding: 672, category: "Legacy System Integration", friction: "Anadolu Efes (750M consumers, 70+ countries, 3,500 employees) faced 'legacy-network-speed-paradox' where network structure had become too complex to support the speed the business required - when connectivity slowed it directly affected sales operations and business continuity", url: "https://www.cloudflare.com/case-studies/anadolu-efes/", severity: "High", company: "Anadolu Efes"}),
  JSON.stringify({finding: 673, category: "Performance and Reliability", friction: "Fullscript (healthcare SaaS, traffic doubling annually for 5 consecutive years) faced 'AWS-WAF-opacity' where AWS WAF gave almost no data when something went wrong - 'We'd have a blocked request and barely any data to figure out why it happened', creating false positives and operational bottlenecks", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"}),
  JSON.stringify({finding: 674, category: "Onboarding & Deployment", friction: "Fullscript faced 'security-rule-change-overhead' where security rule changes consumed more than 4 hours per modification due to unintuitive UI and cumbersome Terraform state management - even simple changes required extensive manual work for healthcare SaaS platform", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"}),
  JSON.stringify({finding: 675, category: "Performance and Reliability", friction: "Fullscript (healthcare SaaS platform) faced 'malicious-traffic-cost-surge' during major security crisis when malicious traffic overwhelmed their platform incurring tens of thousands of dollars daily in infrastructure costs - needed immediate threat identification and mitigation", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"}),
  JSON.stringify({finding: 676, category: "Developer Experience", friction: "Tightknit (lean B2B SaaS startup for community platforms on Slack) faced 'infra-distraction-paradox' where team was determined to avoid headaches of managing servers, complicated Docker files, and risks of running global app on large traditional cloud provider - 'We like solving business problems, not infrastructure'", url: "https://www.cloudflare.com/case-studies/tightknit/", severity: "Medium", company: "Tightknit"}),
  JSON.stringify({finding: 677, category: "Performance and Reliability", friction: "Fullscript (healthcare SaaS platform,3-person infrastructure team) faced 'security-crisis-response-delay' where during major security crisis they couldn't identify where bad traffic was coming from - Cloudflare Security Analytics Dashboard found and blocked bad traffic within 15 minutes saving days of expensive downtime", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"})
];
lines.forEach((l, i) => {
  fs.appendFileSync('research_log.jsonl', l + '\n');
  console.log('Written finding', 668 + i);
});
const after = fs.readFileSync('research_log.jsonl', 'utf8').split('\n').filter(l => l.trim()).length;
console.log('After:', after);