const fs = require('fs');
const lines = [
  JSON.stringify({finding: 622, category: "Security and Governance", friction: "Stack Overflow faced 'AI-era-traffic-shift' where human traffic declined but automated scraping surged - AI bots turned Stack Overflow content into highly valuable target, requiring edge security that could eliminate DDoS impact and block bots at scale", url: "https://www.cloudflare.com/case-studies/stack-overflow/", severity: "High", company: "Stack Overflow"}),
  JSON.stringify({finding: 623, category: "Integration", friction: "Canva (260M monthly users, 190 countries) faced 'acquisition-infra-mismatch' where integrating new acquisitions brought cloud-native tech startups alongside organizations with legacy VPNs and on-premise infrastructure - needed single platform to apply modern security standards across heterogeneous environments", url: "https://www.cloudflare.com/case-studies/canva/", severity: "High", company: "Canva"}),
  JSON.stringify({finding: 624, category: "Legacy System Integration", friction: "Skyscanner (100M monthly users, 80B prices/day, 30 languages) faced 'vpn-complexity-drag' where traditional on-premises architecture strained under hybrid work, with teams expending huge amounts of time and resources just keeping everything online and managing all the infrastructure behind the scenes", url: "https://www.cloudflare.com/case-studies/skyscanner/", severity: "High", company: "Skyscanner"}),
  JSON.stringify({finding: 625, category: "Onboarding & Deployment", friction: "Kaizen Gaming (13M customers, Betano sports betting platform) faced 'websocket-scale-bottleneck' where 600K concurrent WebSocket connections required ~300 custom servers just for real-time data, with routing global traffic back to Europe causing high latency during live betting", url: "https://www.cloudflare.com/case-studies/kaizen-gaming/", severity: "High", company: "Kaizen Gaming"}),
  JSON.stringify({finding: 626, category: "Security and Governance", friction: "Intility (650+ customers, 50K users, 2,500 locations in Scandinavia) faced 'multi-tenant-app-sprawl' where hosting1,000+ different web applications for multiple clients across multiple verticals with unique security requirements created mounting pressure from global DDoS and sophisticated automated threats", url: "https://www.cloudflare.com/case-studies/intility/", severity: "High", company: "Intility"}),
  JSON.stringify({finding: 627, category: "Onboarding & Deployment", friction: "Fullscript (healthcare SaaS platform, traffic doubling annually for 5 consecutive years) faced 'aws-waf-false-positives' where AWS first-gen WAF generated false positives, security rule changes consumed4+ hours per modification, and a3-person team wore multiple hats with mounting operational friction", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"}),
  JSON.stringify({finding: 628, category: "Onboarding & Deployment", friction: "Tightknit (lean startup, community platform for B2B SaaS) faced 'infrastructure-vs-product-tradeoff' where lean teams wanted to focus on building great products and features rather than managing servers, Docker files, and traditional cloud provider complexity", url: "https://www.cloudflare.com/case-studies/tightknit/", severity: "Medium", company: "Tightknit"})
];
lines.forEach((l, i) => {
  fs.appendFileSync('research_log.jsonl', l + '\n');
  console.log('Written finding', 622 + i);
});
const after = fs.readFileSync('research_log.jsonl', 'utf8').split('\n').filter(l => l.trim()).length;
console.log('After:', after);