const fs = require('fs');
const lines = [
  JSON.stringify({finding: 694, category: "Integration", friction: "Intility (650 customers, 50,000 users across Scandinavia) faced 'multi-vendor-tool-sprawl' where fragmented multi-vendor security tools across diverse customer base created complexity - consolidated onto Cloudflare's connectivity cloud running WAF, DDoS protection, Bot Management, CDN, DNS, and Zero Trust on single platform", url: "https://www.cloudflare.com/case-studies/intility/", severity: "High", company: "Intility"}),
  JSON.stringify({finding: 695, category: "Performance and Reliability", friction: "Fullscript (healthcare SaaS, millions of practitioners) faced 'traffic-doubling-dilemma' where web application traffic doubled annually for5 consecutive years - legacy infrastructure unable to support explosive growth demands of healthcare technology sector", url: "https://www.cloudflare.com/case-studies/fullscript/", severity: "High", company: "Fullscript"}),
  JSON.stringify({finding: 696, category: "Performance and Reliability", friction: "Skyscanner (100M customers monthly, travel metasearch) faced 'VPN-backhaul-latency' where with hybrid work policy, VPN backhauled traffic through regional servers leading to inconsistent performance and latency - employees needed safe and scalable access from anywhere in the world", url: "https://www.cloudflare.com/case-studies/skyscanner/", severity: "High", company: "Skyscanner"}),
  JSON.stringify({finding: 697, category: "Integration", friction: "Skyscanner (travel aggregator, 30+ languages, 80B prices daily) used Cloudflare as 'connective tissue' to automate and scale protections across global workforce - engineers now manage access and security through same CI/CD pipelines used for application development", url: "https://www.cloudflare.com/case-studies/skyscanner/", severity: "High", company: "Skyscanner"}),
  JSON.stringify({finding: 698, category: "Performance and Reliability", friction: "Kaizen Gaming (real-time sports betting, 400,000 events livestreamed, 1.5M events/year) faced 'websocket-scale-bottleneck' where at peak 600,000 concurrent client connections needed ~300 custom servers (each pod handles ~2,000 SignalR connections) just for WebSocket connections - created unwieldy resource-intensive configuration", url: "https://www.cloudflare.com/case-studies/kaizen-gaming/", severity: "High", company: "Kaizen Gaming"}),
  JSON.stringify({finding: 699, category: "Security and Governance", friction: "Anadolu Efes (10th largest beer producer globally, 750M consumers, 70+ countries) faced 'legacy-network-security-gap' where 'Attackers only see Cloudflare IPs, they cannot see our internal infrastructure, which limits what they can attack' - needed unified security for sales operations, logistics, and analytics platforms", url: "https://www.cloudflare.com/case-studies/anadolu-efes/", severity: "High", company: "Anadolu Efes"}),
  JSON.stringify({finding: 700, category: "Performance and Reliability", friction: "Discord (2.4M concurrent users, Google Cloud customer) faced 'websocket-outage-cost' where every single outage resulted in frustrated customers and new customers retained poorly due to bad first impressions - Cloudflare serves over 2 Pb of Discord's traffic per month from edge cache and handles websocket spikes up to 2 million/second", url: "https://www.cloudflare.com/case-studies/discord/", severity: "High", company: "Discord"})
];
lines.forEach((l, i) => {
  fs.appendFileSync('research_log.jsonl', l + '\n');
  console.log('Written finding', 694 + i);
});
const after = fs.readFileSync('research_log.jsonl', 'utf8').split('\n').filter(l => l.trim()).length;
console.log('After:', after);