const fs = require('fs');
const lines = [
  JSON.stringify({finding: 660, category: "Security and Governance", friction: "Discord (2.4M concurrent users, online gaming platform) faced 'gamer-DDoS-paradox' where gamers love to DDoS each other during game matches - as Discord grew more popular the intensity and occurrences of DDoS attacks increased to the point where engineers were constantly dealing with them", url: "https://www.cloudflare.com/case-studies/discord/", severity: "High", company: "Discord"}),
  JSON.stringify({finding: 661, category: "Performance and Reliability", friction: "Discord faced 'outage-retention-damage' where every single outage resulted in frustrated customers - new customers who signed up during issues retained poorly due to very bad first impressions, pushing Discord further from goal of becoming de-facto communication app for gamers", url: "https://www.cloudflare.com/case-studies/discord/", severity: "High", company: "Discord"}),
  JSON.stringify({finding: 662, category: "Performance and Reliability", friction: "Discord (gaming communication platform, Google Cloud customer) saves over $100,000 monthly on Google Cloud bill by using Cloudflare CDN - over 2 Pb of Discord's traffic per month is served directly from Cloudflare's edge-side cache", url: "https://www.cloudflare.com/case-studies/discord/", severity: "High", company: "Discord"}),
  JSON.stringify({finding: 663, category: "Security and Governance", friction: "Stack Overflow (millions of engineers, AI era) faced 'AI-scraping-surge' where human traffic declined but automated scraping surged as their content became highly valuable target for bots and AI crawlers - content that took years to create now being stolen at scale", url: "https://www.cloudflare.com/case-studies/stack-overflow/", severity: "High", company: "Stack Overflow"}),
  JSON.stringify({finding: 664, category: "Performance and Reliability", friction: "Stack Overflow (SaaS knowledge platform) faced 'CDN-delay-blips' where previous CDN's local agents at each ingress point introduced delays as distributed systems attempted to block attacks - traffic spikes caused visible site 'blips' lasting several seconds for users", url: "https://www.cloudflare.com/case-studies/stack-overflow/", severity: "High", company: "Stack Overflow"}),
  JSON.stringify({finding: 665, category: "Onboarding & Deployment", friction: "Stack Overflow needed to migrate CDN from Fastly in just 1 month when it normally takes 6 months - included translating Fastly VCL (Varnish Configuration Language) logic to Terraform while DDoS attacks were escalating", url: "https://www.cloudflare.com/case-studies/stack-overflow/", severity: "High", company: "Stack Overflow"}),
  JSON.stringify({finding: 666, category: "Security and Governance", friction: "Stack Overflow (small SRE team of3) faced 'bot-management-scale-mismatch' where bot traffic grew to represent most inbound requests - Cloudflare Bot Management lets their team of 3 handle what requires 'two giant teams' of 25-30 people at other companies", url: "https://www.cloudflare.com/case-studies/stack-overflow/", severity: "High", company: "Stack Overflow"}),
  JSON.stringify({finding: 667, category: "Developer Experience", friction: "Skyscanner (100M customers monthly, hybrid work) faced 'VPN-firefighting-drain' where engineers spent huge amounts of time keeping everything online and every vulnerability exposure required immediate out-of-hours action - complexity of managing infrastructure behind scenes slowed down product development", url: "https://www.cloudflare.com/case-studies/skyscanner/", severity: "High", company: "Skyscanner"})
];
lines.forEach((l, i) => {
  fs.appendFileSync('research_log.jsonl', l + '\n');
  console.log('Written finding', 660 + i);
});
const after = fs.readFileSync('research_log.jsonl', 'utf8').split('\n').filter(l => l.trim()).length;
console.log('After:', after);